### ISSUE TITLE
Fixed left column

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#10]
This will be looked into after #5 is resolved.

Left column in all case studies should be fixed when scrolling

**Comment by longmeaghan** [comment]
@wellcda Made the merge but when I pulled it up, I got this
<img width="1440" alt="screen shot 2018-07-29 at 3 59 53 pm" src="https://user-images.githubusercontent.com/6629178/43371527-8c6c8728-9348-11e8-82c0-08035f2150b9.png">

**Comment by longmeaghan** [comment]
One on Shockoe.php looks correct on desktop, but overlaps on mobile
<img width="504" alt="screen shot 2018-07-29 at 6 50 47 pm" src="https://user-images.githubusercontent.com/6629178/43373728-6e4d3040-9360-11e8-8554-1f20b14cf5fc.png">
<img width="1440" alt="screen shot 2018-07-29 at 6 50 38 pm" src="https://user-images.githubusercontent.com/6629178/43373729-6e69e46a-9360-11e8-88da-41fb6da8c233.png">

**Comment by wellcda** [comment]
I'm sure it is fixed now, if it doesn't seem so try using CTRL+SHIFT+R to clean cache.
