### ISSUE TITLE
Header bottom padding

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#42]
I tried adding a margin-bottom: 24px and a padding-bottom: 24px; to the header with no luck. It just needs some breathing room between the title of the page and the header
<img width="397" alt="screen shot 2018-08-04 at 11 28 45 pm" src="https://user-images.githubusercontent.com/6629178/43683339-38e1d5a4-983e-11e8-8305-8792fa28a96c.png">

**Comment by wellcda** [comment]
It's not possible to add margin/padding to the navbar due to the way it's positioned. To "fix" this try adding some `margin-top` to the `.container-fluid` class. Right now the margin is only 90px.

**Comment by wellcda** [comment]
Fixed on #52.
