### ISSUE TITLE
Padding in links

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#44]
I added padding between links in the header to give them breathing room. However, it did not work locally, but seems to work in inspector. Not sure why Chrome would be accepting these changes in the inspector but my local code would not. 

<img width="962" alt="screen shot 2018-08-04 at 11 24 32 pm" src="https://user-images.githubusercontent.com/6629178/43683383-3cd8c658-983f-11e8-9be0-e77f2dfb128f.png">

**Comment by wellcda** [comment]
Fixed on #52.
