### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#45]
This is working correctly on Safari, but not on Chrome or Firefox.

https://github.com/longmeaghan/ml_portfolio/blob/6bc586488e5b9b1bea5ec3e874ddf0ca545dc396/htdocs/head.php#L16

- [x] **Safari**
<img width="1440" alt="screen shot 2018-08-04 at 11 41 33 pm" src="https://user-images.githubusercontent.com/6629178/43683420-2d6fb6d0-9840-11e8-987b-f7e1fa301a95.png">

- [x] **Firefox**
<img width="335" alt="screen shot 2018-08-04 at 11 42 27 pm" src="https://user-images.githubusercontent.com/6629178/43683418-2d413008-9840-11e8-9fca-6fc87e8a08a8.png">

- [x] **Chrome**
<img width="279" alt="screen shot 2018-08-04 at 11 42 09 pm" src="https://user-images.githubusercontent.com/6629178/43683419-2d593c2a-9840-11e8-9b52-a3ba02d6eb60.png">

**Comment by wellcda** [comment]
Seems to be working fine on Chrome and Firefox.

**Chrome**
![image](https://user-images.githubusercontent.com/8882404/43686939-eead4aac-98a3-11e8-8dc2-80db158b306e.png)

**Firefox**
![image](https://user-images.githubusercontent.com/8882404/43686931-d600e68a-98a3-11e8-987b-fe518057613a.png)

Have you cleaned cache on these browsers?

**Comment by wellcda** [comment]
It's also working fine on the server so don't worry!

**Comment by wellcda** [comment]
Can i close this issue? Seems to be working fine both on my machine and on server.

**Comment by wellcda** [comment]
Fixed on #52.
