### ISSUE TITLE
Header overlapping col-md-3

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#5]
https://github.com/longmeaghan/ml_portfolio/blob/ad8bc65242d6d8457a62e87569de2c3e4a1b88f7/htdocs/index.css#L320-L333

Made an `@media max-width` with appropriate changes for the header when it hits 575px. Unfortunately the header is overlapping where the col-md-3 is, which that extra top-padding it provides would be really useful to have between the title of the page and the header. 
 
*Intentionally have the `background: blue;` to see better how everything is laying*

**Comment by longmeaghan** [comment]
<img width="1437" alt="screen shot 2018-07-13 at 11 05 11 pm" src="https://user-images.githubusercontent.com/6629178/42721661-5570ac42-86f3-11e8-84ce-66e4405ac642.png">

**Comment by wellcda** [comment]
Pull request #18 should fix this issue.
