### ISSUE TITLE
Removing .php on website

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#6]
The `.html` in the address needs to be removed before it's live

**Comment by longmeaghan** [comment]
After larger issues are completed, refer to this [documentation](https://alexcican.com/post/how-to-remove-php-html-htm-extensions-with-htaccess/).

**Comment by longmeaghan** [comment]
I found this document but was still confused. Maybe we can do a phone call to talk about this one? Would like to learn
http://roshanbh.com.np/2008/02/hide-php-url-rewriting-htaccess.html

**Comment by longmeaghan** [comment]
Made merge in #34. Verified and closing.

**Comment by wellcda** [comment]
The .htacess works fine for Apache, but doesn't work for Nginx. It all depends on what our host will be running on. Still, is something easy to do that should be done when the server is up.
